packages:
  - .
  - examples/*

catalog:
  '@types/react': ^19
  '@types/react-dom': ^19
  eslint: ^9
  graphql: ^16
  next: ^15.2.0-canary.57
  next-auth: ^5.0.0-beta.25
  react: ^19
  react-dom: ^19
  prettier: ^3
  tailwindcss: ^4
  typescript: ^5.7.3
  zustand: ^5.0.3
  zod: ^3